name: Build and run tests
on:
  push:
  # pull_request: # Don't run twice
jobs:
  flakes-simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v5
        with:
          nix_version: 2.4pre20201205_a5d85d0
          nix_conf: experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: cclaw
          # If you chose signing key for write access
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/cache@v2.1.5
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
      - name: Initial nix develop
        run: nix develop --profile .dev-profile -c sh -c 'which stack; which gf; echo $GF_LIB_PATH'
      - name: stack deps
        run: nix develop --profile .dev-profile -c stack build --nix --only-dependencies
      - name: stack build
        # if: false()
        # TODO: Don't use --nix. Use actions/haskell instead
        # Or just do it without nix and let stack install ghc
        # but then we don't get other fancieness from haskell actions
        run: nix develop --profile .dev-profile -c stack build --nix --test --no-run-tests || echo "::warning file=app.js,line=1,col=5::Failure"
      - name: stack test
        # if: false()
        run: nix develop --profile .dev-profile -c stack test --nix || echo "::warning file=app.js,line=1,col=5::Failure"